### ISSUE TITLE
Update license to "GPLv2 and later" to solve conflict with Apache2 support libs

### ISSUE THREAD

**Issue by krt16s** [phikal/ReGeX#1]
The app uses the Android support libraries, which are Apache2 licensed. However, plain GPLv2 is not compatible with it, but GPLv2+ (with the "and later" addition) is. Could you explicitly state this is the correct version, e.g. in the readme? The included license file covers both versions of the gplv2.

**Comment by phikal** [comment]
Done: 00cacf37d947fb4e89fa4b46d8acf51322581b89
