### ISSUE TITLE
Explain regex chars and their functions ingame

### ISSUE THREAD

**Issue by lightonflux** [phikal/ReGeX#10]
The game lacks explanation. People that hope to learn regex via this game will be disappointed.

An ingame explanation or maybe even tutorial would defiantly help for beginners.

**Comment by phikal** [comment]
The info popup mentioned in #9 could have  two options: "Start game" and "show tutorial". The latter will introduce the player to the concept of regular expressions and how to play the game. Sounds good?

**Comment by burningTyger** [comment]
Might add a link to http://www.cheatography.com/davechild/cheat-sheets/regular-expressions/ which is optimized for mobile devices, too. Otherwise a NEAT idea for a game.

**Comment by phikal** [comment]
Added @burningTyger's link and fixed with 6aaed03e6f4d9aadb4f2ec17262ea58c904018ee and #9
