### ISSUE TITLE
Screen rotation changes the current puzzle

### ISSUE THREAD

**Issue by kozross** [phikal/ReGeX#11]
If you rotate the screen to horizontal, and then back to vertical, the current puzzle changes to a new one.

**Comment by MoonZ** [comment]
same issue here: Nexus 5, Android 5.1.1 SDK version 22

When the puzzle changes, the round number stays the same (so I guess it's not in sync anymore).
'reset the game' doesn't provide a work-around to this issue, the current puzzle stays the same.

**Comment by phikal** [comment]
I'm still not sure whether I should actually find out what the issue is, or just disable screen rotation. I haven't tried it on tablets yet, so I'm not sure how it works there. Any suggestions?

**Comment by kozross** [comment]
I wouldn't suggest disabling screen rotation - I often play ReGeX on a phone, and locking it into the vertical position would be a real pain.

**Comment by phikal** [comment]
Closed with ab74a0faaabcdeba4a7cd417f4523237a91aac97
