### ISSUE TITLE
Translate to different languages

### ISSUE THREAD

**Issue by phikal** [phikal/ReGeX#13]
I am currently working on German and Serbo-Croation translation. Any help would be great.

**Comment by nico202** [comment]
Id translate into Italian:)

**Comment by phikal** [comment]
@nico202 Cool, do you know how to do it or do you need help?

**Comment by phikal** [comment]
Italian was implemented with Pull request #15.

**Comment by phikal** [comment]
I just realized that there would be a problem with the Update log: Every time the application is updated, we would have to translate the log as well, which would mean that we would have to wait for a translator to be as friendly to help us OR we just kept in English for all languages OR we just leave it out. I personally would be for the second option, although the last one is the easiest, but any other arguments are welcomed

**Comment by nico202** [comment]
Maybe for non-critical bugs we can have a X hours deadline, if translators translate, the log is added in their language, else in english. But I don't know if will work

**Comment by phikal** [comment]
@nico202 could you translate the new strings for v1.3? If not, please tell me.

**Comment by nico202** [comment]
Yup

Il 5 settembre 2016 03:34:10 CEST, "Philip K." <notifications@github.com> ha scritto:
>@nico202 could you translate the new strings for v1.3? If not, please
>tell me.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/phikal/ReGeX/issues/13#issuecomment-244641654

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by nico202** [comment]
Pull request #25

**Comment by phikal** [comment]
Since people have been contributing translations, unrelated to this issue, I'll close it.
