### ISSUE TITLE
Unable to use template chars (such as ?) from regular keyboard

### ISSUE THREAD

**Issue by KOLANICH** [phikal/ReGeX#2]
(I use [Hackers' Keyboard](https://f-droid.org/repository/browse/?fdid=org.pocketworkstation.pckeyboard) )

**Comment by phikal** [comment]
I am not quite sure as to what the problem is... What happens when you click on `?` on your keyboard? Dose it not appear or is some other problem?

**Comment by KOLANICH** [comment]
Nothing. And it seems that it is only in the beginning, now (a am on lvl 8) it works.

**Comment by KOLANICH** [comment]
Reseted the game. Working... Seems to be one time glitch.
