### ISSUE TITLE
Doesen't work

### ISSUE THREAD

**Issue by OffifialMITX** [phikal/ReGeX#27]
ReGeX does not start since the last upgrade on F-Droid. Android 5.1.1 .

**Comment by phikal** [comment]
Do you have any logs? I conscious how ironic this may sound, but _it works on my device_.

**Comment by YgrekIx** [comment]
I confirm, first run all ok, second run, just screen flash and nothing.
Great idea/game. Thank You

**Comment by YgrekIx** [comment]
Another tip, after clearing "data", app works again.

**Comment by phikal** [comment]
@Ygreklx what Android version are you running?

**Comment by YgrekIx** [comment]
Android 6.0
Huawei P9 eva-l9
If your application store somewhere logs, tell me where and I paste it to you :)

**Comment by phikal** [comment]
No, I'm sorry, the application doesn't store logs on files, but you might be able to catch the error with adb logcat.

This site might help you, in case you don't have too mich experience on the subject: http://wiki.cyanogenmod.org/w/Doc:_debugging_with_logcat

**Comment by YgrekIx** [comment]
True, I must force app crashing again :)

**Comment by OffifialMITX** [comment]
The backgroud color appears for maybe 200ms then I see my launcher again. I've solved this problem by deleting any apps data, now it works, thanks, @Ygreklx .

**Comment by phikal** [comment]
@YgrekIx So, could you make a log? I'm just asking because there could be a connection to #29, and I still don't know what's wrong.

**Comment by YgrekIx** [comment]
[RegExLog.txt](https://github.com/phikal/ReGeX/files/584025/RegExLog.txt)

Got IT! :) This started in random game mode.

**Comment by phikal** [comment]
Great, thanks for the log.

All in all the following lines seem to be relevant:
```
11-10 18:37:00.118  2285  3291 W PGApi_client: recv actoionId = 10000, action = com.huawei.pgmng.PGAction@7ac87ab actionId =10000 pkg =com.phikal.regex extend1 =2114 extend2 = flag =3 type =1
11-10 18:37:00.154 25467 25467 W System  : ClassLoader referenced unknown path: /data/app/com.phikal.regex-1/lib/arm64
11-10 18:37:00.165 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.168 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.174 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.175 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.176 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.177 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.179 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.180 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.180 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.182 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.184 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.187 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.191 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.192 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.193 25467 25467 W ZipFileCache: Open zip file:com.phikal.regex failed!
11-10 18:37:00.215   562  1022 I logserver: extract_appname, forward search, appname=com.phikal.regex
11-10 18:37:00.216   562  1022 I logserver: get_fault_appname, appname=com.phikal.regex
11-10 18:37:00.217   562  1021 I logserver: handle_notify_event, send msg [submit:trigger=0,bugtype=2,modulename=com.phikal.regex,level=1,testtype=NORMAL,path=/data/log/unzip/EVA-L09_EVA-L09C432B180_0000000000_20161110183700_crash,mode=1;]
```

The most prominent error being `ZipFileCache: Open zip file:... failed`, and then looking this kind of error up, I found [this stackoverflow post](https://stackoverflow.com/questions/33669464/android-logcat-error-zipfilecache-init-failed-when-open-zip-file-device-spec). It seems to be tied, to Huawei devices, so it's not going to be easy to fix that. I know a guy with a Huawei, so I'll ask him if he could help me.

So all in all, I would further conclude there being no obvious tie to #29. 

@OffifialMITX what device were you using when this happened? As far as I understood, it crashed after updating from 1.2, so was it totally fixed after @YgrekIx's suggestion to clear app data?

**Comment by OffifialMITX** [comment]
Yes, you go that right, I've updated from 1.2 to 1.3 directly after F-Droid released it. After I have cleared app data it never had problems with it anymore.

I'm using the Neffos C5L from TP-LINK .

**Comment by the0ne** [comment]
11-22 10:10:07.922 I/ActivityManager(881): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.phikal.regex/.Activities.GameActivity bnds=[111,1440][309,1656] (has extras)} from uid 10303 on display 0
11-22 10:10:07.972 I/ActivityManager(881): Start proc 839:com.phikal.regex/u0a181 for activity com.phikal.regex/.Activities.GameActivity
11-22 10:10:08.072 W/System  (839): ClassLoader referenced unknown path: /data/app/com.phikal.regex-1/lib/arm
11-22 10:10:08.145 E/AndroidRuntime(839): Process: com.phikal.regex, PID: 839
11-22 10:10:08.145 E/AndroidRuntime(839): java.lang.RuntimeException: Unable to resume activity {com.phikal.regex/com.phikal.regex.Activities.GameActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
11-22 10:10:08.145 E/AndroidRuntime(839):         at com.phikal.regex.Activities.GameActivity.getName(Unknown Source)
11-22 10:10:08.145 E/AndroidRuntime(839):         at com.phikal.regex.Activities.GameActivity.onResume(Unknown Source)
11-22 10:10:08.146 W/ActivityManager(881):   Force finishing activity com.phikal.regex/.Activities.GameActivity
11-22 10:10:08.741 W/ActivityManager(881): Activity pause timeout for ActivityRecord{9f98210 u0 com.phikal.regex/.Activities.GameActivity t424077 f}
11-22 10:10:09.605 I/ActivityManager(881): Process com.phikal.regex (pid 839) has died
11

**Comment by phikal** [comment]
Since @the0ne's log also refers to #29, and that is "closed", I'm going to close this issue too for now.
