### ISSUE TITLE
Random language generation needed

### ISSUE THREAD

**Issue by hackerb9** [phikal/ReGeX#34]
I am excited for this game as I love solving regular expressions. In the real world, regexes allow you to match not just some finite set of words, but all possible words of a certain type. The puzzle and the fun is in recognizing the pattern that groups the words together so you can craft the perfect regex.

This game has promise, but its random problem generator only creates strings of characters with no rhyme or reason. I just played 66 rounds and got to level 10 and every single solution was "[abc].*" or a minor variant of it. It was boring because the type of problem never changed.

I think it would be much more fun if the set of words was created by randomly created regexes, finite state automata or hidden Markov models.

For example, if the game randomly creates "a+", the first level might look like:

Match: a aaaaaa  aaaa
Not: b abba baa

As levels progress, instead of the words getting longer, the generating pattern will get more complex, randomly adding regex features like matching groups and alternation. 

For example, perhaps the next level would increase the grammar (which letters are allowed) and the problem generated might be "[ab]",

Match: a b
Not: c

And then,

Match:  aa abab bbbb
Not:  a bab abba

If you make a list of regex features ordered by difficulty, you can add new ones in the mix after each level. That way the game would constantly feel like a significantly different challenge as new types of patterns appear.

Thanks for making what promises to be a great game.

**Comment by phikal** [comment]
Defiantly sounds interesting, certainly worth building into the game - I'll set it up as a milestone.

But I'd have to revise some language theory, before trying to implement this, since I've never spent too much time with these things. But it will probably take a while, since I'm preoccupied with other stuff for the moment.

**Comment by phikal** [comment]
This should be solved with 9e3317b61870fd6b06b10288ab7f675a0e2966fa. [RegularExpression](https://github.com/phikal/ReGeX/blob/6937071e3877cb3c425360f0005173f1df3abbd8/app/src/main/java/com/phikal/regex/models/RegularExpression.java) should be able to offer a functioning framework for random-but-challenging games, hopefully solving the issue you brought up. 

Now it will just need some more tweaks and improvements, that should come along with testing.

**Comment by hackerb9** [comment]
Fabulous! I look forward to play testing this as soon as F-droid updates the apk.

**Comment by phikal** [comment]
Well, there are still a few other pending issues and general restructuring needed before I can tag a new version, so it might still take a while...
