### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [phikal/ReGeX#35]
When I perform this sequence of events, the scroll view on screen goes back to the top

1. In the first help dialog, scroll down
2. Orientation Change

**Comment by phikal** [comment]
Which scroll view are you refering to? "Match" and "Don't match"?

**Comment by reverse-unina** [comment]
The scroll view inside the dialog that appears right after install

**Comment by phikal** [comment]
The one with "ReGeX /ˈrɛːɡɛx/ is an android game, with a simple objective: [...]"?

**Comment by reverse-unina** [comment]
Yes, it's him!

**Comment by phikal** [comment]
I'm afraid that's the native behaviour of a scroll view element, so there isn't much I can do about it. As far as [I see](http://stackoverflow.com/a/24703937), as soon as a scroll element looses focus, it goes back to the top, and element (I believe) always loose and regain focus when rotated. 

One possible solution I could think of spontaneously would be to [memorize the position](https://developer.android.com/reference/android/view/View.html#onScrollChanged(int,%20int,%20int,%20int))  and [reset it](https://developer.android.com/reference/android/widget/ScrollView.html#scrollTo(int,%20int)) every time the activity is reloaded. 

But other than some slight visual pleasure in not having to scroll down a bit after rotating a device in an (more or less) irrelevant dialog, I don't think the code or the effort in writing/maintaining this would be worth it. 

So, spontaneously I'd close this issue, but I'm just going to ask if you have some specific argument for having to fix this?

**Comment by reverse-unina** [comment]
I am exploring GUI failures for research purposes. As stated by Android guidelines after an orientation change, apps should preserve their state and functional parity.  Thanks to your contribution, it is emerging that there are some limitations in the Android framework and high coding effort are required in certain situations.

**Comment by phikal** [comment]
Ah, ok, I'm glad that I could help.

But just regarding the

>high coding effort are required

it's not that it's a lot of effort to write it _per se_, but rather when thinking about issues, like #31, that bugs appear over time related to such "manual fixes". The code would probably be 20-30 lines max., so I just wanted to mention that for your research.

So all in all, I'll consider this "fixed" for now, unless anyone protests.
