### ISSUE TITLE
Text changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [phikal/ReGeX#37]
When I perform this sequence of events, the text view returns to its default value:

1. Click on Settings
2. Click on Reset Game
3. Orientation Change

**Comment by phikal** [comment]
Why shouldn't the text view be reset when you reset the game?

**Comment by reverse-unina** [comment]
When i press "Reset Game" the text changes in "Press to Confirm"
After the orientation change, the text returns to "Reset Game" instead of retaining "Press to Confirm"

**Comment by phikal** [comment]
Ah, ok, I get it. I have an idea on how to fix it, and I'll try and get around to do it as soon as possible.

**Comment by phikal** [comment]
Fixed with 90b7eb2254ff6306dedb380e653b417b66168446
