### ISSUE TITLE
All puzzles are easy to solve by using |

### ISSUE THREAD

**Issue by POTION4** [phikal/ReGeX#4]

**Comment by phikal** [comment]
Could you describe how to recreate the bug?

**Comment by lightonflux** [comment]
Not just "|" but the amount of allowed chars and easy hits make it possible to solve with "x|ua" and so one. Played for five mins in a row and everything™ was solvable with |.

**Comment by POTION4** [comment]
@phikal yeah, all puzzles can be solved by |. Such as aux|bcd.

**Comment by phikal** [comment]
The amount of allowed characters should be exactly `"sum of length of all to-be-matched words" + "amount of words to be matched" - 1" `  for this solution to be a last escape. The points received by using this method should be as low as possible, on higher levels this might even cost you a level. 

But as mentioned in #3, the games maths still require some optimization, and I hope I (or anyone) will be able to fix it as soon as possible.

**Comment by phikal** [comment]
Closed with #3. All I mentioned there is also true for this issue.
