### ISSUE TITLE
Highest level

### ISSUE THREAD

**Issue by ameenross** [phikal/ReGeX#53]
What is the highest achievable level? I've been at 13 for the longest time and though it was the highest, then I just did one puzzle today (after a long pause) and I suddenly got LVL 14.

**Comment by phikal** [comment]
There is no intended highest level, but as mentioned in #51 the current implementation is so meaningless that it might be that there is an effective, unintentional limit that is difficult  to surpass.

**Comment by ameenross** [comment]
In that case my question is how does leveling work? I though it was simply based on total amount of points, or # puzzles solved. But apparently it isn't.

**Comment by phikal** [comment]
That is done here:

https://github.com/phikal/ReGeX/blob/b2d3563f6528692d1cd8ab30c9293a0a7c7b6b99/app/src/main/java/com/phikal/regex/Utils/Calc.java#L51

A few random constants, with inverse quadratic growth by the score, divided by the number of completed puzzles.  The code was written almost 7 years ago, and I just want to emphasize that I had no idea what I was doing, so there is no deeper meaning to this.
