### ISSUE TITLE
Question: why not matched

### ISSUE THREAD

**Issue by mmahmoudian** [phikal/ReGeX#54]
I think this should be correct what am I doing wrong?

![Screenshot_20220603-182745~2](https://user-images.githubusercontent.com/390889/171886397-ec707299-3fdc-445a-83e2-9a63c8531cd2.png)

**Comment by phikal** [comment]
The game requires the regular expressions to match the entire word, not just a substring.  Your attempt would only match strings of the form `L`, `LL`, `LLwL`, `wLLL`, `wwwww`, etc.

**Comment by mmahmoudian** [comment]
You are right. It would be nice to show somehow that it has matched substring but not the full words. Right now it seems regardless of what I have typed, nothing is happening. That was my source of confusion.

Thanks for this simple and yet engaging game

**Comment by phikal** [comment]
I plan to rewrite the game some day (see #47), when that happens I will keep that in mind.
