### ISSUE TITLE
How many levels are there?

### ISSUE THREAD

**Issue by nico202** [phikal/ReGeX#6]
I'm stuck at 9. Also, in the level-success popup, it would be usefeful to see if you went up or down

**Comment by phikal** [comment]
There is no limit on hof far the level counter can go, but you have realized a bug mentioned in #3, that around level 8-9 it get's really hard to level up. It's all just maths, so all I or anyone has to do is optimize the function. 

I'm going to add the level popup to the TODO list.

**Comment by phikal** [comment]
Implemented level popup with 4bbe2a632d7672e3f7faad08bb4d2031d643e5fe
