### ISSUE TITLE
Option: disable vibration and/or sound

### ISSUE THREAD

**Issue by lightonflux** [phikal/ReGeX#7]
It is not possible to play the game while listening to music. It just always stops the music.

And the vibration gets annoying if you put your phone on a wooden or glass table while playing.

**Comment by nico202** [comment]
Music keep playing on mine. Maybe it depends on the player 

On August 2, 2015 1:18:46 AM GMT+02:00, lightonflux <notifications@github.com> wrote:
>It is not possible to play the game while listening to music. It just
>always stops the music.
>
>And the vibration gets annoying if you put your phone on a wooden or
>glass table while playing.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/phikal/ReGeX/issues/7

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by phikal** [comment]
When long pressing on the character counter, there will
be  statistics and settings popup when you can see an option to turn of vibration.

The version popup mentioned in #9 will either inform the player about the settings option or I could maybe add another settings button on the right next to the text input box.

**Comment by phikal** [comment]
Implemented settings button on the right with 7ede1e82c66111bd80e70c1b676e085d72db288f. The rest has been solved in #9
