### ISSUE TITLE
Show amount of solved problem

### ISSUE THREAD

**Issue by lightonflux** [phikal/ReGeX#8]
Just so the player knows about his her progress.

**Comment by phikal** [comment]
I will add this to settings and statistics mentioned in #9.

**Comment by phikal** [comment]
Actually I just realize that you can already see this in the settings... Should have closed this a while ago.

**Comment by lightonflux** [comment]
I did not know there is a settings menu, it is hard to discover. Could you add a gear icon and / or menu-button support? The gear icon could be in the right of the input field.
