### ISSUE TITLE
explain game objective ingame

### ISSUE THREAD

**Issue by lightonflux** [phikal/ReGeX#9]
So what do you need to do? Imagine I haven't read the readme or the fdroid description. And just installed it because of its relation to regex.

**Comment by phikal** [comment]
I will add a info popup that will tell the player what to do or what's new every time the game is either updated or started for the first time. That should be enough, shouldn't it?

**Comment by phikal** [comment]
Implemented with 6aaed03e6f4d9aadb4f2ec17262ea58c904018ee
